/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/callback': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Exchange magic-link token for a session */
    get: operations['get_callback_api_v1_auth_callback_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/csrf-refresh': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Force-rotate the CSRF token (clears the existing cookie)
     * @description Explicit endpoint to rotate the CSRF cookie.
     *
     *     Useful for tooling / Selenium that wants a fresh token without going
     *     through ``/auth/callback``.
     */
    post: operations['post_csrf_refresh_api_v1_auth_csrf_refresh_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/logout': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Clear the session cookie
     * @description Clear the session cookie and revoke its JTI so the token cannot replay.
     */
    post: operations['post_logout_api_v1_auth_logout_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/magic-link': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Request a magic login link
     * @description Issue a magic-link email.
     *
     *     Always returns 204 — we deliberately do NOT distinguish between "user
     *     exists / email sent" and "delivery failed" so we can't be used as an
     *     account-existence oracle. Internal observability still records the
     *     failure via :func:`loguru.warning`.
     */
    post: operations['post_magic_link_api_v1_auth_magic_link_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Return the authenticated user */
    get: operations['get_me_api_v1_auth_me_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update the caller's profile (P0-6 — display_name only)
     * @description Update the caller's mutable profile fields.
     *
     *     Currently the only mutable field is ``display_name`` (handle changes
     *     are not supported in MVP per P0_DESIGN §P0-6 "Open decisions").
     *     The schema's ``extra='forbid'`` makes a client that POSTs ``handle``
     *     fail at validation with a 422 + a typed FE error.
     */
    patch: operations['patch_me_api_v1_auth_me_patch'];
    trace?: never;
  };
  '/api/v1/auth/me/consent': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Return the caller's most-recent consent decision per kind (P0-5)
     * @description Return the latest ``UserConsent`` per kind for the authenticated user.
     *
     *     Each of the three kinds (``analytics``, ``functional``, ``marketing``)
     *     surfaces either the most-recent decision (by ``granted_at``) or
     *     ``None`` when no row exists. The endpoint is read-only and side-effect
     *     free; the FE polls it on app boot to decide whether the cookie banner
     *     needs to render.
     */
    get: operations['get_me_consent_api_v1_auth_me_consent_get'];
    put?: never;
    /**
     * Record a consent decision (append-only audit trail) (P0-5)
     * @description Insert a new ``UserConsent`` row + emit a ``consent.*`` event.
     *
     *     Append-only by design: replaying a POST writes a new row rather than
     *     mutating an existing one, so the FULL consent history is recoverable
     *     for a regulator. The server stamps ``version`` from
     *     ``settings.consent_policy_version`` — the client cannot influence the
     *     recorded policy version.
     *
     *     The supervision-style event lands on the dedicated ``account_events``
     *     table (the platform's main ``supervision_events`` table requires a
     *     NOT NULL session FK, and consent is account-scoped, not session-scoped).
     *     The same table now also carries the P0-6 ``account.*`` events — see
     *     :class:`AccountEvent` for the full event-type allow-list.
     */
    post: operations['post_me_consent_api_v1_auth_me_consent_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me/data-export': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Kick off an asynchronous account data-export job (P0-6)
     * @description Insert a ``queued`` row and enqueue the export worker.
     *
     *     Returns 409 if there is already a ``queued`` or ``running`` export for
     *     this user — the partial unique index enforces this at the DB layer on
     *     Postgres, but we also check at the application layer for SQLite (which
     *     ignores ``WHERE`` on unique indexes) AND as defence-in-depth.
     *
     *     If the RQ queue is unreachable we fall back to running the worker
     *     inline in the request loop — same pattern as ``provision_in_process``.
     */
    post: operations['post_me_data_export_api_v1_auth_me_data_export_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me/data-export/{export_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Poll a data-export job and (if ready) get a signed download URL (P0-6) */
    get: operations['get_me_data_export_api_v1_auth_me_data_export__export_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me/delete': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Schedule the caller's account for hard deletion in 7 days (P0-6) */
    post: operations['post_me_delete_api_v1_auth_me_delete_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me/delete/cancel': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Cancel a pending account deletion during the grace window (P0-6) */
    post: operations['post_me_delete_cancel_api_v1_auth_me_delete_cancel_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me/email/change': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Start the two-step email-change flow (P0-6)
     * @description Set ``users.pending_email`` and email a magic link to the NEW address.
     *
     *     Validation:
     *
     *     * New email must be syntactically valid (Pydantic ``EmailStr``).
     *     * New email must not equal an existing ``users.email`` or
     *       ``users.pending_email`` of any account (409 on collision).
     *     * The caller's account must not be scheduled for deletion (the
     *       :class:`DeletionLockMiddleware` enforces this — by the time this
     *       handler runs, ``user.deletion_scheduled_at`` is guaranteed NULL).
     */
    post: operations['post_me_email_change_api_v1_auth_me_email_change_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me/email/confirm': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Confirm an in-flight email change (P0-6)
     * @description Consume the email-change token and land the new email atomically.
     *
     *     Server-side checks:
     *
     *     * Token must be valid + unused + not expired (consume_email_change_token
     *       handles all three).
     *     * Token's ``user_id`` must equal the calling user's id.
     *     * ``user.pending_email`` must still be set (cleared by another path
     *       would mean the user already confirmed via a different device).
     *
     *     After the email lands we rotate the session epoch — every cookie minted
     *     before this moment is now invalid except the one we mint right here.
     */
    post: operations['post_me_email_confirm_api_v1_auth_me_email_confirm_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me/sessions/sign-out-all': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Invalidate every other live session for the caller (P0-6)
     * @description Bump the user's session_epoch and mint a fresh cookie for the caller.
     *
     *     Other devices' cookies will fail verification on their next request.
     *     The current caller keeps their session via the fresh cookie attached
     *     to the response.
     */
    post: operations['post_me_sign_out_all_api_v1_auth_me_sessions_sign_out_all_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/auth/me/tutorial/replay': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Clear tutorial completion + increment replay count (P0-1)
     * @description Re-arm the tutorial coachmark for the signed-in user.
     *
     *     Atomic: a single SQL ``UPDATE`` clears ``tutorial_completed_at`` and
     *     increments ``tutorial_replay_count`` server-side. The previous
     *     Python-side read-modify-write lost increments under concurrent
     *     replays (two callers each read N, both wrote N+1).
     */
    post: operations['post_tutorial_replay_api_v1_auth_me_tutorial_replay_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/missions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List published missions */
    get: operations['list_missions_api_v1_missions_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/missions/{mission_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Mission detail */
    get: operations['get_mission_detail_api_v1_missions__mission_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/profiles/me/skills': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Per-failure-mode mastery summary for the logged-in user
     * @description Return the failure-mode catalog with the user's attempt/pass stats.
     *
     *     The catalog groups the 10 supervision failure modes (one per mission)
     *     and reports, for each, the user's attempt count, pass count, and
     *     average + best total score. A "pass" is a session whose score_report
     *     has ``missed_failure_mode == False``.
     */
    get: operations['get_my_skills_api_v1_profiles_me_skills_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/profiles/{handle}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get a user's public profile by handle
     * @description Return the public profile for ``handle``.
     *
     *     No authentication required — public surface per §13.1. Returns 404 with
     *     ``{"detail": "profile not found"}`` when no user owns this handle.
     *
     *     The detailed per-dimension longitudinal trail is only returned to the
     *     profile owner themselves — anonymous and other-user viewers see the
     *     radar averages but not the trend per session. This avoids leaking a
     *     fingerprintable skill trajectory of any user by handle.
     */
    get: operations['get_profile_api_v1_profiles__handle__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reports/{submission_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve a grading report by submission id
     * @description Return a graded submission.
     *
     *     Authorisation succeeds if either of:
     *       - The caller is signed in AND owns the submission's session.
     *       - A valid ``?share=<jwt>`` query param decodes to this submission id.
     *
     *     All other callers receive 403 (or 401 when neither cookie nor share is
     *     present).
     */
    get: operations['get_report_api_v1_reports__submission_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reports/{submission_id}/print': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Internal: full report payload for the print-mode worker (P0-11)
     * @description Worker-only endpoint that returns the same SubmissionRead shape as
     *     ``GET /reports/{id}`` but authorises by ``X-Render-Token`` header
     *     instead of by session ownership / share token. The token is an
     *     HMAC over the submission id signed with ``VERIFY_SECRET``.
     *
     *     The route is intentionally undocumented in the public surface — the
     *     worker's bridge constructs the URL itself and the FE never hits it.
     */
    get: operations['get_report_for_print_api_v1_reports__submission_id__print_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reports/{submission_id}/render': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve or queue a PDF/PNG render (P0-11)
     * @description Owner-or-share endpoint that returns a signed URL when ready.
     *
     *     Lifecycle:
     *       * row missing → enqueue a fresh render → 202
     *       * status=queued|running → 202 with poll_after_seconds
     *       * status=ready → 302 to a 5-minute signed R2 URL
     *       * status=failed → 503 with the worker's error message
     */
    get: operations['get_render_api_v1_reports__submission_id__render_get'];
    put?: never;
    /**
     * Force re-render a PDF/PNG (owner only) (P0-11)
     * @description Owner-only: drop any existing row + enqueue a fresh render.
     *
     *     Idempotent during ``queued`` / ``running`` — a second call sees the
     *     in-flight row and returns it without re-enqueuing. Rate-limited at
     *     ``settings.report_render_force_daily_cap`` force re-renders per
     *     submission per 24h so a user can't cycle the cached PDF.
     */
    post: operations['post_render_api_v1_reports__submission_id__render_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/reports/{submission_id}/share': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Mint a 30-day share token for a report
     * @description Owner-only: returns the share URL and token (TTL 30d).
     */
    post: operations['post_share_api_v1_reports__submission_id__share_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create a session */
    post: operations['post_session_api_v1_sessions_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions/{session_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read a session */
    get: operations['get_session_endpoint_api_v1_sessions__session_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions/{session_id}/commands': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Run a command in the sandbox */
    post: operations['post_command_api_v1_sessions__session_id__commands_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions/{session_id}/context': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Update session context selection */
    post: operations['post_context_api_v1_sessions__session_id__context_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions/{session_id}/diff': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get the workspace diff from initial state */
    get: operations['get_diff_api_v1_sessions__session_id__diff_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions/{session_id}/events/diff-opened': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Record that the user opened the diff viewer (for scoring + badges)
     * @description Emits a ``diff.opened`` supervision event.
     *
     *     Driven by the frontend DiffViewer the first time it mounts with a
     *     non-empty diff. The score engine's "Agent Output Review" dimension
     *     (§11.2.4) checks for this event after ``patch.applied`` to award up to
     *     +6 points; without it, the dimension is hard-capped.
     *
     *     Accepts an optional ``{"path": "..."}`` body so the timeline can name the
     *     specific file the user opened. An empty body is still accepted for
     *     backwards compatibility with older clients.
     */
    post: operations['post_diff_opened_api_v1_sessions__session_id__events_diff_opened_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions/{session_id}/events/tutorial-step': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Record a tutorial coachmark step transition (P0-1)
     * @description Persist a ``tutorial.step_completed`` or ``tutorial.dismissed`` event.
     *
     *     These events are tutorial-only — the grader ignores them (Mission 00
     *     short-circuits the scoring path entirely). Persisting them via the
     *     supervision-event log keeps the audit trail uniform with every other
     *     user action, which is the load-bearing invariant for the post-mortem
     *     replay tool.
     */
    post: operations['post_tutorial_step_api_v1_sessions__session_id__events_tutorial_step_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions/{session_id}/file': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read a file from the sandbox */
    get: operations['get_file_api_v1_sessions__session_id__file_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions/{session_id}/files': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Write a file in the sandbox */
    post: operations['post_file_api_v1_sessions__session_id__files_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions/{session_id}/files/revert': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Revert a file to its initial state */
    post: operations['post_revert_api_v1_sessions__session_id__files_revert_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions/{session_id}/give-up': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Forfeit the session, reveal the ideal solution, cap the score at 50
     * @description Forfeit the active session and immediately submit it for grading.
     *
     *     Preconditions:
     *       * The caller owns the session.
     *       * ``session.status == 'active'`` (a session that's already submitting
     *         or graded can't be given up on — the user must wait for the
     *         in-flight grade to finish, then they can retry).
     *       * At least :data:`GIVE_UP_MIN_SECONDS` (10 min) have elapsed since
     *         ``session.started_at`` — prevents quitting before engaging.
     *
     *     Side-effects (in order):
     *       1. Emit ``session.gave_up`` supervision event with the
     *          ``seconds_into_session`` payload (so the timeline reflects the
     *          deliberate forfeit).
     *       2. Stamp ``sessions.gave_up_at = now()``. The grading runner reads
     *          this flag when computing the score report and applies a 50/100
     *          cap with ``score_cap_reason='gave_up'``.
     *       3. Call the standard submit pipeline (same path as
     *          ``POST /sessions/{id}/submit``).
     *
     *     Errors:
     *       * 409 — session is not active (already graded, abandoned, errored,
     *         or mid-submit). Detail includes the current status.
     *       * 425 (Too Early) — 10-min window hasn't elapsed yet. Detail
     *         carries ``seconds_remaining`` so the FE can render a countdown.
     */
    post: operations['post_give_up_api_v1_sessions__session_id__give_up_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions/{session_id}/patches/{turn_id}/apply': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Apply the agent patch for a specific turn (no request body)
     * @description Apply the agent-proposed patch for ``turn_id``.
     *
     *     Takes no request body — the (turn_id, session_id) tuple in the URL is
     *     the only input. The previous ``ApplyPatchBody`` placeholder model was
     *     removed (P1-B9): nothing consumed it and publishing an empty schema as
     *     part of the public OpenAPI surface led FE generators to mint a useless
     *     type alias.
     */
    post: operations['post_apply_patch_api_v1_sessions__session_id__patches__turn_id__apply_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions/{session_id}/prompts': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Submit a prompt and get an agent response */
    post: operations['post_prompt_api_v1_sessions__session_id__prompts_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions/{session_id}/reset': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset the workspace to the mission's initial commit (P0-12)
     * @description Roll the sandbox back to ``mission.initial_commit``.
     *
     *     Preconditions:
     *       * the caller owns the session,
     *       * ``session.status == 'active'`` (the mutability gate),
     *       * the sandbox handle is alive (the existing 503 path).
     *
     *     Side effects (in order):
     *       1. ``git status --porcelain`` → count discarded files (telemetry).
     *       2. ``git reset --hard <initial_commit>``.
     *       3. ``git clean -fd`` — drops untracked files + directories.
     *       4. Emit ``session.reset`` with
     *          ``{files_discarded, had_agent_patch, seconds_into_session}``.
     *       5. Insert a ``FileChange(source='revert', path='*')`` so the file-
     *          change audit trail records the wipe.
     *
     *     Concurrency note: the existing apply-patch path holds no per-handle
     *     lock today (see ``app/sandbox/pool.py``). A reset issued while a
     *     patch is mid-apply may race; the workspace store is single-tab so
     *     the FE side rarely produces this. A future hardening pass should
     *     add a per-handle ``asyncio.Lock`` and wrap both apply-patch and
     *     reset in it.
     */
    post: operations['post_reset_api_v1_sessions__session_id__reset_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions/{session_id}/submission': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Retrieve the grading result for a session
     * @description Return the grading submission for an already-graded session.
     *
     *     Returns 404 if the session has not been submitted yet, or 404 if the
     *     session itself does not exist. ``ideal_solution`` /
     *     ``ideal_solution_diff`` / ``agent_patch_diff`` are injected from disk
     *     when ``session.status == 'graded'`` so the FE can render the
     *     post-mortem walkthrough (P0-2) without a second roundtrip to
     *     ``/reports``.
     */
    get: operations['get_submission_api_v1_sessions__session_id__submission_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions/{session_id}/submit': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Submit a session for grading
     * @description Trigger the grading pipeline for a session.
     *
     *     Returns 200 with the final ``SubmissionRead`` once grading completes
     *     (the call blocks until the runner returns; see ``sessions/submit.py``).
     */
    post: operations['post_submit_api_v1_sessions__session_id__submit_post'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions/{session_id}/timeline': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Return the supervision event timeline for the session */
    get: operations['get_timeline_api_v1_sessions__session_id__timeline_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions/{session_id}/tree': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List the sandbox file tree */
    get: operations['get_tree_api_v1_sessions__session_id__tree_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/sessions/{session_id}/ws-token': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Mint a short-lived WS auth token */
    get: operations['get_ws_token_api_v1_sessions__session_id__ws_token_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** API status (v1 alias for public /status) */
    get: operations['status_v1_api_v1_status_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/verify/{submission_id}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Public verification page envelope (P0-11)
     * @description Anonymous endpoint that renders the verification envelope.
     *
     *     No auth required — the URL is the credential. Returns 404 when:
     *       * the submission does not exist,
     *       * the session is not yet graded (mid-pipeline),
     *       * the mission is a tutorial (tutorials are not credentialing),
     *       * the verification hash + signature were never stamped.
     *
     *     The response is cacheable for a year + immutable: a graded
     *     submission's envelope is frozen forever (the hash pins it). The
     *     ``X-Robots-Tag`` header tells crawlers the URL is intended to be
     *     indexed — that's the verification path a recruiter follows when they
     *     Google the URL.
     */
    get: operations['get_verify_api_v1_verify__submission_id__get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/healthz': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness probe
     * @description Cheap liveness probe — no DB / Redis touches.
     *
     *     Kubernetes / load balancers should hit this every second; the heavier
     *     DB+Redis check lives at ``/healthz/ready``.
     */
    get: operations['healthz_healthz_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/healthz/ready': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Readiness probe
     * @description Full readiness check with bounded per-probe timeouts.
     *
     *     Returns HTTP 200 when the DB, Redis, and sandbox runtime are reachable.
     *     When any of those three fail we return the same JSON body with HTTP 503
     *     so load balancers and Kubernetes can de-list the pod. ``s3_ok`` is
     *     treated as best-effort and does NOT force 503 — object storage is not on
     *     the request hot-path for every endpoint, and a transient S3 hiccup
     *     shouldn't take traffic away from the API.
     */
    get: operations['healthz_ready_healthz_ready_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Public status page
     * @description Aggregated, human-readable system status. Cached for 10s. Mirrors the components probed by ``/healthz/ready`` plus uptime and version.
     */
    get: operations['status_status_get'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /**
     * AgentTurnResponse
     * @description One agent reply, including any actions the user can perform on it.
     */
    AgentTurnResponse: {
      /** Agent Response */
      agent_response: string;
      /** Applied Patch */
      applied_patch?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Patch Applied At */
      patch_applied_at?: string | null;
      /** Proposed Actions */
      proposed_actions?: string[];
      selected_context: components['schemas']['ContextSelection'];
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string;
      /** Turn Index */
      turn_index: number;
      /** User Prompt */
      user_prompt: string;
    };
    /** CommandBody */
    CommandBody: {
      /**
       * Category
       * @default other
       * @enum {string}
       */
      category: 'test' | 'typecheck' | 'lint' | 'manual' | 'other';
      /** Command */
      command: string;
    };
    /**
     * CommandRunResponse
     * @description Response returned after running a command in the sandbox.
     *
     *     ``stdout``/``stderr`` are truncated by the route handler to
     *     :data:`MAX_STDIO_BYTES` and ``stdio_truncated`` is set when the tail was
     *     trimmed so the FE can show a hint.
     */
    CommandRunResponse: {
      /**
       * Category
       * @default other
       * @enum {string}
       */
      category: 'test' | 'typecheck' | 'lint' | 'manual' | 'other';
      /** Command */
      command: string;
      /** Created At */
      created_at?: string | null;
      /** Duration Ms */
      duration_ms?: number | null;
      /** Exit Code */
      exit_code?: number | null;
      /** Id */
      id: string;
      /** Session Id */
      session_id: string;
      /**
       * Stderr
       * @default
       */
      stderr: string;
      /**
       * Stdio Truncated
       * @default false
       */
      stdio_truncated: boolean;
      /**
       * Stdout
       * @default
       */
      stdout: string;
    };
    /**
     * ConsentRecord
     * @description Latest persisted consent decision for a single kind.
     */
    ConsentRecord: {
      /**
       * At
       * Format: date-time
       */
      at: string;
      /** Granted */
      granted: boolean;
      /** Version */
      version: number;
    };
    /**
     * ConsentState
     * @description Per-kind snapshot of the user's most recent decision (or None).
     *
     *     A field is ``None`` when no row exists yet for that kind. Once the
     *     user posts at least one decision (granted or revoked), the field
     *     surfaces the most recent record.
     */
    ConsentState: {
      analytics?: components['schemas']['ConsentRecord'] | null;
      functional?: components['schemas']['ConsentRecord'] | null;
      marketing?: components['schemas']['ConsentRecord'] | null;
    };
    /**
     * ConsentUpdate
     * @description POST body — kind to record and whether the user granted or revoked.
     *
     *     The server stamps ``version`` from settings (the current policy
     *     version) and never trusts a client-supplied version field.
     */
    ConsentUpdate: {
      /** Granted */
      granted: boolean;
      /**
       * Kind
       * @enum {string}
       */
      kind: 'analytics' | 'functional' | 'marketing';
    };
    /**
     * ContextSelection
     * @description The set of artifacts the user has selected as relevant for the turn.
     */
    ContextSelection: {
      /** Extras */
      extras?: string[];
      /** Files */
      files?: string[];
      /** Logs */
      logs?: string[];
      /** Tests */
      tests?: string[];
    };
    /**
     * DataExportRead
     * @description Serialised :class:`app.models.data_export.DataExport`.
     *
     *     ``download_url`` is populated by the route only when the export is in
     *     ``ready`` state AND has not yet expired — a presigned URL signed in
     *     real time so the URL's lifetime cannot outlive the export's lifetime.
     */
    DataExportRead: {
      /** Bytes Total */
      bytes_total?: number | null;
      /** Download Url */
      download_url?: string | null;
      /** Error */
      error?: string | null;
      /** Expires At */
      expires_at?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Ready At */
      ready_at?: string | null;
      /**
       * Requested At
       * Format: date-time
       */
      requested_at: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'queued' | 'running' | 'ready' | 'failed' | 'expired';
    };
    /**
     * DeleteAccountRequest
     * @description Body for ``POST /me/delete`` — re-type the email to confirm intent.
     */
    DeleteAccountRequest: {
      /**
       * Confirm Email
       * Format: email
       */
      confirm_email: string;
    };
    /**
     * DeletionLockError
     * @description 403 envelope returned by :class:`DeletionLockMiddleware`.
     *
     *     Pydantic model so the OpenAPI surface declares the exact shape every
     *     mutating P0-6 endpoint may return while the account is mid-grace. The
     *     FE keys off ``code == 'deletion_scheduled'`` to render the "your
     *     account is scheduled for deletion" banner instead of a generic 403.
     *
     *     ``scheduled_for`` is included so the FE can render the same countdown
     *     used on the ``/account`` page without re-fetching ``/auth/me``.
     */
    DeletionLockError: {
      /**
       * Code
       * @constant
       */
      code: 'deletion_scheduled';
      /**
       * Detail
       * @description Human-readable detail string. The FE keys off ``code`` for routing decisions; ``detail`` is only surfaced to support.
       */
      detail: string;
      /**
       * Scheduled For
       * Format: date-time
       */
      scheduled_for: string;
    };
    /**
     * DeletionScheduledRead
     * @description Response body for ``POST /me/delete``.
     */
    DeletionScheduledRead: {
      /**
       * Scheduled For
       * Format: date-time
       */
      scheduled_for: string;
    };
    /**
     * DiffOpenedBody
     * @description Optional body for ``/events/diff-opened`` — surfaces which file was opened.
     */
    DiffOpenedBody: {
      /**
       * Path
       * @default
       */
      path: string;
    };
    /**
     * DimensionTrendPoint
     * @description One ``(completed_at, score)`` point on a per-dimension sparkline.
     */
    DimensionTrendPoint: {
      /**
       * Completed At
       * Format: date-time
       */
      completed_at: string;
      /** Score */
      score: number;
    };
    /**
     * DisplayNameUpdate
     * @description Body for ``PATCH /me``.
     *
     *     ``handle`` is intentionally absent: per P0_DESIGN §P0-6 ("Open
     *     decisions" → "Handle changes"), the public profile URL is stable, so
     *     we reject handle changes at the schema layer rather than rejecting at
     *     the route layer (which gives the FE a typed error instead of a 422).
     */
    DisplayNameUpdate: {
      /**
       * Display Name
       * @description New display name (≤120 chars, no leading/trailing whitespace).
       */
      display_name?: string | null;
    };
    /**
     * EarnedBadgeRead
     * @description Badge plus when/where it was earned (from ``user_badges``).
     */
    EarnedBadgeRead: {
      /** Description */
      description: string;
      /**
       * Earned At
       * Format: date-time
       */
      earned_at: string;
      /** Icon */
      icon: string;
      /** Id */
      id: string;
      /** Session Id */
      session_id?: string | null;
      /** Title */
      title: string;
    };
    /**
     * EmailChangeConfirm
     * @description Body for ``POST /me/email/confirm`` — the raw magic-link token.
     */
    EmailChangeConfirm: {
      /** Token */
      token: string;
    };
    /**
     * EmailChangeRequest
     * @description Body for ``POST /me/email/change``.
     */
    EmailChangeRequest: {
      /**
       * New Email
       * Format: email
       */
      new_email: string;
    };
    /**
     * FailureModeMastery
     * @description Per-failure-mode mastery summary for the logged-in user (P2-3).
     *
     *     Powers the "skills" / "failure-mode catalog" page: the user sees, for
     *     each of the 10 supervision failure modes, how many sessions they
     *     attempted, how many they passed (hidden tests green), and their
     *     average score across attempts.
     */
    FailureModeMastery: {
      /** Avg Score */
      avg_score?: number | null;
      /** Best Score */
      best_score?: number | null;
      /** Failure Mode */
      failure_mode: string;
      /** Failure Mode Title */
      failure_mode_title?: string | null;
      /** Last Attempted At */
      last_attempted_at?: string | null;
      /** Mission Ids */
      mission_ids?: string[];
      /** Mission Titles */
      mission_titles?: string[];
      /**
       * Sessions Attempted
       * @default 0
       */
      sessions_attempted: number;
      /**
       * Sessions Passed
       * @default 0
       */
      sessions_passed: number;
    };
    /**
     * FileContent
     * @description `GET /sessions/{id}/file` response body.
     *
     *     The frontend type mirror lives in
     *     ``packages/shared-types/src/api.ts`` and is generated from this model
     *     via ``openapi-typescript``. ``encoding`` reports whether the file was
     *     safe to decode as UTF-8 (``"utf-8"``) or had to be returned as
     *     base64-encoded bytes for binary content (``"base64"``).
     */
    FileContent: {
      /** Content */
      content: string;
      /**
       * Encoding
       * @default utf-8
       * @enum {string}
       */
      encoding: 'utf-8' | 'base64';
      /**
       * Path
       * @default
       */
      path: string;
      /**
       * Truncated
       * @default false
       */
      truncated: boolean;
    };
    /** FileRevertBody */
    FileRevertBody: {
      /** Path */
      path: string;
    };
    /**
     * FileTreeNodeSchema
     * @description Frontend-compatible file-tree node.
     *
     *     Converts the sandbox ``FileTreeNode`` dataclass, which uses ``kind="dir"``,
     *     into the shape the frontend expects: ``kind="directory"``, plus a ``name``
     *     field derived from the path basename.
     */
    FileTreeNodeSchema: {
      /** Children */
      children?: components['schemas']['FileTreeNodeSchema'][];
      /**
       * Kind
       * @enum {string}
       */
      kind: 'file' | 'directory';
      /** Name */
      name: string;
      /** Path */
      path: string;
      /** Size */
      size?: number | null;
    };
    /** FileWriteBody */
    FileWriteBody: {
      /** Content */
      content: string;
      /** Path */
      path: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][];
    };
    /** MagicLinkRequest */
    MagicLinkRequest: {
      /**
       * Email
       * Format: email
       */
      email: string;
    };
    /**
     * MissionDetail
     * @description `GET /missions/{id}` payload.
     *
     *     Withholds ``ideal_solution`` and any hidden-test surface; brief is included
     *     because the workspace needs it.
     */
    MissionDetail: {
      /**
       * Brief
       * @default
       */
      brief: string;
      /**
       * Category
       * @enum {string}
       */
      category:
        | 'auth'
        | 'testing'
        | 'security'
        | 'frontend'
        | 'api'
        | 'database'
        | 'refactoring'
        | 'agent-safety'
        | 'review'
        | 'debugging'
        | 'tutorial';
      /**
       * Difficulty
       * @enum {string}
       */
      difficulty: 'beginner' | 'intermediate' | 'advanced';
      /** Estimated Minutes */
      estimated_minutes: number;
      /** Expected Context Recommended */
      expected_context_recommended?: string[];
      /** Expected Context Required */
      expected_context_required?: string[];
      /** Expected Diff Lines P50 */
      expected_diff_lines_p50?: number | null;
      /** Failure Mode Id */
      failure_mode_id: string;
      /** Id */
      id: string;
      /** Initial Commit */
      initial_commit: string;
      /**
       * Kind
       * @default standard
       * @enum {string}
       */
      kind: 'standard' | 'tutorial';
      /** Language Runtime */
      language_runtime?: ('node20' | 'python312') | null;
      /** Manifest Sha256 */
      manifest_sha256: string;
      /**
       * Published
       * @default true
       */
      published: boolean;
      /** Repo Pack */
      repo_pack: string;
      /**
       * Short Description
       * @default
       */
      short_description: string;
      /** Skills Tested */
      skills_tested?: string[];
      /** Title */
      title: string;
      /**
       * Version
       * @default 1
       */
      version: number;
      /** Visible Tests */
      visible_tests?: string[];
      your_attempts?: components['schemas']['YourAttempts'] | null;
    };
    /**
     * MissionHistoryItemRead
     * @description A single graded session entry on a user's profile.
     */
    MissionHistoryItemRead: {
      /** Completed At */
      completed_at?: string | null;
      /**
       * Difficulty
       * @enum {string}
       */
      difficulty: 'beginner' | 'intermediate' | 'advanced';
      /** Mission Id */
      mission_id: string;
      /** Mission Title */
      mission_title: string;
      /** Score */
      score?: number | null;
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string;
    };
    /**
     * MissionListItem
     * @description Minimal mission card payload for `GET /missions`.
     */
    MissionListItem: {
      /**
       * Category
       * @enum {string}
       */
      category:
        | 'auth'
        | 'testing'
        | 'security'
        | 'frontend'
        | 'api'
        | 'database'
        | 'refactoring'
        | 'agent-safety'
        | 'review'
        | 'debugging'
        | 'tutorial';
      /**
       * Difficulty
       * @enum {string}
       */
      difficulty: 'beginner' | 'intermediate' | 'advanced';
      /** Estimated Minutes */
      estimated_minutes: number;
      /** Failure Mode Id */
      failure_mode_id: string;
      /** Id */
      id: string;
      /**
       * Kind
       * @default standard
       * @enum {string}
       */
      kind: 'standard' | 'tutorial';
      /**
       * Published
       * @default true
       */
      published: boolean;
      /**
       * Short Description
       * @default
       */
      short_description: string;
      /** Skills Tested */
      skills_tested?: string[];
      /** Title */
      title: string;
      /**
       * Version
       * @default 1
       */
      version: number;
    };
    /** PatchResult */
    PatchResult: {
      /**
       * Added Lines
       * @default 0
       */
      added_lines: number;
      /** Applied */
      applied: boolean;
      /** Error */
      error?: string | null;
      /** Files Changed */
      files_changed?: string[];
      /**
       * Removed Lines
       * @default 0
       */
      removed_lines: number;
    };
    /**
     * PromptBody
     * @description POST body for ``/sessions/{id}/prompts``.
     *
     *     Bounded at 20k characters — anything beyond is pathological for a
     *     supervision prompt and would balloon DB rows + WS event payloads.
     */
    PromptBody: {
      context?: components['schemas']['ContextSelection'] | null;
      /** Text */
      text: string;
    };
    /**
     * PublicProfile
     * @description Payload of `GET /api/v1/profiles/{handle}`.
     *
     *     Public — no auth required, never include PII.
     */
    PublicProfile: {
      /** Badges */
      badges?: components['schemas']['EarnedBadgeRead'][];
      /** Best Score */
      best_score?: number | null;
      /** Dimension Trends */
      dimension_trends?: {
        [key: string]: components['schemas']['DimensionTrendPoint'][];
      };
      /** Display Name */
      display_name?: string | null;
      /** Handle */
      handle: string;
      /** History */
      history?: components['schemas']['MissionHistoryItemRead'][];
      /**
       * Joined At
       * Format: date-time
       */
      joined_at: string;
      /** Radar Averages */
      radar_averages?: {
        [key: string]: number;
      };
      /**
       * Total Missions
       * @default 0
       */
      total_missions: number;
    };
    /**
     * ReportRenderRead
     * @description Lifecycle row for the PDF / PNG render pipeline (P0-11).
     *
     *     Returned by ``GET /api/v1/reports/{id}/render?kind=…`` when the
     *     render is still in flight, and by ``POST /api/v1/reports/{id}/render``
     *     when a force-render is enqueued. When ``status == 'ready'`` the
     *     route 302s to a signed URL instead of returning this body — the FE
     *     only sees this shape during the queued / running / failed lifecycle.
     */
    ReportRenderRead: {
      /** Bytes */
      bytes?: number | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Error */
      error?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /**
       * Kind
       * @enum {string}
       */
      kind: 'pdf' | 'png';
      /** Poll After Seconds */
      poll_after_seconds?: number | null;
      /** Ready At */
      ready_at?: string | null;
      /**
       * Status
       * @enum {string}
       */
      status: 'queued' | 'running' | 'ready' | 'failed';
      /**
       * Submission Id
       * Format: uuid
       */
      submission_id: string;
    };
    /** SessionCreate */
    SessionCreate: {
      /** Mission Id */
      mission_id: string;
      /** Previous Session Id */
      previous_session_id?: string | null;
    };
    /**
     * SessionDetail
     * @description `GET /sessions/{id}` response — adds workspace bootstrap material.
     */
    SessionDetail: {
      /**
       * Agent Turns
       * @default 0
       */
      agent_turns: number;
      /**
       * Attempt Index
       * @default 1
       */
      attempt_index: number;
      /** Completed At */
      completed_at?: string | null;
      /** Current Commit */
      current_commit?: string | null;
      /** Gave Up At */
      gave_up_at?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      mission: components['schemas']['MissionDetail'];
      /** Mission Id */
      mission_id: string;
      /** Previous Session Id */
      previous_session_id?: string | null;
      /**
       * Sandbox Driver
       * @default local
       * @enum {string}
       */
      sandbox_driver: 'docker' | 'local';
      /** Sandbox Id */
      sandbox_id?: string | null;
      /** Score */
      score?: number | null;
      /**
       * Started At
       * Format: date-time
       */
      started_at: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'provisioning' | 'active' | 'submitting' | 'graded' | 'abandoned' | 'error';
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
      /** Ws Token */
      ws_token: string;
    };
    /**
     * SessionRead
     * @description Bare session row — used as the response for `POST /sessions`.
     */
    SessionRead: {
      /**
       * Agent Turns
       * @default 0
       */
      agent_turns: number;
      /**
       * Attempt Index
       * @default 1
       */
      attempt_index: number;
      /** Completed At */
      completed_at?: string | null;
      /** Current Commit */
      current_commit?: string | null;
      /** Gave Up At */
      gave_up_at?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Mission Id */
      mission_id: string;
      /** Previous Session Id */
      previous_session_id?: string | null;
      /**
       * Sandbox Driver
       * @default local
       * @enum {string}
       */
      sandbox_driver: 'docker' | 'local';
      /** Sandbox Id */
      sandbox_id?: string | null;
      /** Score */
      score?: number | null;
      /**
       * Started At
       * Format: date-time
       */
      started_at: string;
      /**
       * Status
       * @enum {string}
       */
      status: 'provisioning' | 'active' | 'submitting' | 'graded' | 'abandoned' | 'error';
      /**
       * User Id
       * Format: uuid
       */
      user_id: string;
    };
    /**
     * SessionResetResponse
     * @description `POST /sessions/{id}/reset` response (P0-12).
     *
     *     Carries the commit HEAD now points to (== mission's initial_commit,
     *     since the workspace is now byte-identical to provision-time), the
     *     count of files the reset discarded (telemetry — read by the FE store
     *     to size the toast), and the running count of reset events on this
     *     session.
     */
    SessionResetResponse: {
      /** Files Reset */
      files_reset: number;
      /** New Head Commit */
      new_head_commit: string;
      /** Reset Count */
      reset_count: number;
    };
    /**
     * ShareTokenRead
     * @description Response payload for ``POST /reports/{id}/share``.
     */
    ShareTokenRead: {
      /**
       * Expires At
       * Format: date-time
       */
      expires_at: string;
      /** Share Token */
      share_token: string;
      /** Share Url */
      share_url: string;
    };
    /**
     * SkillsCatalog
     * @description Payload of ``GET /api/v1/profiles/me/skills``.
     */
    SkillsCatalog: {
      /** Failure Modes */
      failure_modes?: components['schemas']['FailureModeMastery'][];
      /**
       * Total Failure Modes
       * @default 0
       */
      total_failure_modes: number;
      /**
       * Total Missions
       * @default 0
       */
      total_missions: number;
    };
    /** SubmissionRead */
    SubmissionRead: {
      /** Agent Patch Diff */
      agent_patch_diff?: string | null;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Critical Moments */
      critical_moments?: {
        [key: string]: unknown;
      }[];
      /**
       * Final Diff
       * @default
       */
      final_diff: string;
      /** Hidden Test Results */
      hidden_test_results?:
        | {
            [key: string]: unknown;
          }[]
        | {
            [key: string]: unknown;
          };
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Ideal Solution */
      ideal_solution?: string | null;
      /** Ideal Solution Diff */
      ideal_solution_diff?: string | null;
      /** Mission Id */
      mission_id?: string | null;
      /** Score Cap Reason */
      score_cap_reason?: 'gave_up' | null;
      /** Score Report */
      score_report?: {
        [key: string]: unknown;
      };
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string;
      /** Total Score */
      total_score: number;
      /** Validator Results */
      validator_results?:
        | {
            [key: string]: unknown;
          }[]
        | {
            [key: string]: unknown;
          };
      /** Verification Hash */
      verification_hash?: string | null;
      /** Verification Signature */
      verification_signature?: string | null;
      /** Visible Test Results */
      visible_test_results?:
        | {
            [key: string]: unknown;
          }[]
        | {
            [key: string]: unknown;
          };
    };
    /**
     * SupervisionEventRead
     * @description A single supervision event from the timeline.
     */
    SupervisionEventRead: {
      /** Event Type */
      event_type: string;
      /** Id */
      id: number;
      /**
       * Occurred At
       * Format: date-time
       */
      occurred_at: string;
      /** Payload */
      payload?: {
        [key: string]: unknown;
      };
      /**
       * Session Id
       * Format: uuid
       */
      session_id: string;
    };
    /**
     * TutorialStepBody
     * @description Body for ``POST /sessions/{id}/events/tutorial-step``.
     *
     *     ``action`` discriminates "I completed step X" from "I dismissed step X"
     *     — both write into the supervision event log so the post-session content
     *     tuning can see exactly which steps users skipped vs. completed. The
     *     grader ignores tutorial events when scoring.
     */
    TutorialStepBody: {
      /**
       * Action
       * @default completed
       * @enum {string}
       */
      action: 'completed' | 'dismissed';
      /** Step Id */
      step_id: string;
    };
    /** UnifiedDiff */
    UnifiedDiff: {
      /** Unified Diff */
      unified_diff: string;
    };
    /** UserRead */
    UserRead: {
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /** Csrf Token */
      csrf_token: string;
      /** Deletion Scheduled At */
      deletion_scheduled_at?: string | null;
      /** Display Name */
      display_name?: string | null;
      /**
       * Email
       * Format: email
       */
      email: string;
      /** Github Login */
      github_login?: string | null;
      /** Handle */
      handle?: string | null;
      /**
       * Id
       * Format: uuid
       */
      id: string;
      /** Last Login At */
      last_login_at?: string | null;
      /** Pending Email */
      pending_email?: string | null;
      /** Tutorial Completed At */
      tutorial_completed_at?: string | null;
      /**
       * Tutorial Replay Count
       * @default 0
       */
      tutorial_replay_count: number;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * VerifyEnvelopeRead
     * @description Public response for ``GET /api/v1/verify/{submission_id}`` (P0-11).
     *
     *     The shape mirrors the canonical envelope verbatim plus three
     *     surface-only fields the FE needs but that are NOT part of the hash:
     *     ``canonical_url`` (so the verify page knows its own URL),
     *     ``verification_hash`` (already computed at grade time), and
     *     ``verification_signature`` (HMAC of the hash). All three are
     *     persisted columns on ``submissions``; the page never re-derives them
     *     server-side because the hash MUST be a function of the row's
     *     grade-time state, never the current state of the joined rows.
     */
    VerifyEnvelopeRead: {
      /** Attempt Index */
      attempt_index: number;
      /** Canonical Url */
      canonical_url: string;
      /** Display Name */
      display_name?: string | null;
      /** Effective Max */
      effective_max: number;
      /** Graded At */
      graded_at: string;
      /** Handle */
      handle: string;
      /** Missed Failure Mode */
      missed_failure_mode: boolean;
      /** Mission Id */
      mission_id: string;
      /** Mission Title */
      mission_title: string;
      /** Mission Version */
      mission_version: number;
      /** Proctored */
      proctored: boolean;
      /** Rubric Version */
      rubric_version: string;
      /** Schema Version */
      schema_version: number;
      /** Score Cap Reason */
      score_cap_reason?: 'gave_up' | null;
      /**
       * Submission Id
       * Format: uuid
       */
      submission_id: string;
      /** Total Score */
      total_score: number;
      /** Verification Hash */
      verification_hash: string;
      /** Verification Signature */
      verification_signature: string;
    };
    /**
     * WsTokenRead
     * @description Response payload for ``GET /sessions/{id}/ws-token``.
     */
    WsTokenRead: {
      /** Token */
      token: string;
      /** Ttl Seconds */
      ttl_seconds: number;
    };
    /**
     * YourAttempts
     * @description P0-3 — the signed-in user's attempt history against a single mission.
     *
     *     Surfaced inline on the mission detail page so the "// your attempts" strip
     *     can render without a second roundtrip. ``count`` is the total graded
     *     attempts (capped + uncapped) so the strip honours the multi-attempt
     *     policy: ``best_score`` reflects the user's best non-gave-up attempt
     *     (falling back to the best gave-up attempt when no uncapped attempt
     *     exists), ``latest_score`` is the most recently graded attempt regardless
     *     of cap, and ``delta`` is the signed difference between latest and first.
     *
     *     Attempt count is NEVER surfaced on the public profile — see
     *     `docs/adr/0009-multi-attempt-policy.md`.
     */
    YourAttempts: {
      /** Best Score */
      best_score?: number | null;
      /** Best Submission Id */
      best_submission_id?: string | null;
      /**
       * Best Was Gave Up
       * @default false
       */
      best_was_gave_up: boolean;
      /**
       * Count
       * @default 0
       */
      count: number;
      /** Delta */
      delta?: number | null;
      /** Latest Score */
      latest_score?: number | null;
      /** Latest Submission Id */
      latest_submission_id?: string | null;
      /** Score History */
      score_history?: number[];
    };
    /** _ForceRenderBody */
    _ForceRenderBody: {
      /** Kind */
      kind: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  get_callback_api_v1_auth_callback_get: {
    parameters: {
      query: {
        /** @description Raw magic-link token from the email URL */
        token: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_csrf_refresh_api_v1_auth_csrf_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  post_logout_api_v1_auth_logout_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_magic_link_api_v1_auth_magic_link_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['MagicLinkRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_me_api_v1_auth_me_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
    };
  };
  patch_me_api_v1_auth_me_patch: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DisplayNameUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
      /** @description Account scheduled for deletion. ``code='deletion_scheduled'`` with ``scheduled_for`` carrying the ISO-8601 grace-end timestamp. Cancel via ``POST /auth/me/delete/cancel`` (the only exempt mutating endpoint). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeletionLockError'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_me_consent_api_v1_auth_me_consent_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ConsentState'];
        };
      };
    };
  };
  post_me_consent_api_v1_auth_me_consent_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ConsentUpdate'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_me_data_export_api_v1_auth_me_data_export_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DataExportRead'];
        };
      };
      /** @description Account scheduled for deletion. ``code='deletion_scheduled'`` with ``scheduled_for`` carrying the ISO-8601 grace-end timestamp. Cancel via ``POST /auth/me/delete/cancel`` (the only exempt mutating endpoint). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeletionLockError'];
        };
      };
    };
  };
  get_me_data_export_api_v1_auth_me_data_export__export_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        export_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DataExportRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_me_delete_api_v1_auth_me_delete_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['DeleteAccountRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeletionScheduledRead'];
        };
      };
      /** @description Account scheduled for deletion. ``code='deletion_scheduled'`` with ``scheduled_for`` carrying the ISO-8601 grace-end timestamp. Cancel via ``POST /auth/me/delete/cancel`` (the only exempt mutating endpoint). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeletionLockError'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_me_delete_cancel_api_v1_auth_me_delete_cancel_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_me_email_change_api_v1_auth_me_email_change_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailChangeRequest'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Account scheduled for deletion. ``code='deletion_scheduled'`` with ``scheduled_for`` carrying the ISO-8601 grace-end timestamp. Cancel via ``POST /auth/me/delete/cancel`` (the only exempt mutating endpoint). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeletionLockError'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_me_email_confirm_api_v1_auth_me_email_confirm_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['EmailChangeConfirm'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
      /** @description Account scheduled for deletion. ``code='deletion_scheduled'`` with ``scheduled_for`` carrying the ISO-8601 grace-end timestamp. Cancel via ``POST /auth/me/delete/cancel`` (the only exempt mutating endpoint). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeletionLockError'];
        };
      };
      /** @description The email change can't be confirmed — either there is no pending change (``no_pending_email``) or the address was claimed by another account before confirm (``email_taken_in_flight``). */
      409: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_me_sign_out_all_api_v1_auth_me_sessions_sign_out_all_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Account scheduled for deletion. ``code='deletion_scheduled'`` with ``scheduled_for`` carrying the ISO-8601 grace-end timestamp. Cancel via ``POST /auth/me/delete/cancel`` (the only exempt mutating endpoint). */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['DeletionLockError'];
        };
      };
    };
  };
  post_tutorial_replay_api_v1_auth_me_tutorial_replay_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UserRead'];
        };
      };
    };
  };
  list_missions_api_v1_missions_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MissionListItem'][];
        };
      };
    };
  };
  get_mission_detail_api_v1_missions__mission_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        mission_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['MissionDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_my_skills_api_v1_profiles_me_skills_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SkillsCatalog'];
        };
      };
    };
  };
  get_profile_api_v1_profiles__handle__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        handle: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PublicProfile'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_report_api_v1_reports__submission_id__get: {
    parameters: {
      query?: {
        /** @description Optional signed share token */
        share?: string | null;
      };
      header?: never;
      path: {
        submission_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SubmissionRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_report_for_print_api_v1_reports__submission_id__print_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        submission_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SubmissionRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_render_api_v1_reports__submission_id__render_get: {
    parameters: {
      query?: {
        /** @description render kind: pdf or png */
        kind?: string;
        /** @description Optional signed share token */
        share?: string | null;
      };
      header?: never;
      path: {
        submission_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
      /** @description Render is queued or running */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Render is ready — Location header carries the signed URL */
      302: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
      /** @description Render failed; retry via POST /render */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  post_render_api_v1_reports__submission_id__render_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        submission_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['_ForceRenderBody'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ReportRenderRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_share_api_v1_reports__submission_id__share_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        submission_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['ShareTokenRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_session_api_v1_sessions_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['SessionCreate'];
      };
    };
    responses: {
      /** @description Successful Response */
      202: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SessionRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_session_endpoint_api_v1_sessions__session_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SessionDetail'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_command_api_v1_sessions__session_id__commands_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CommandBody'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['CommandRunResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_context_api_v1_sessions__session_id__context_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ContextSelection'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_diff_api_v1_sessions__session_id__diff_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['UnifiedDiff'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_diff_opened_api_v1_sessions__session_id__events_diff_opened_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        'application/json': components['schemas']['DiffOpenedBody'] | null;
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_tutorial_step_api_v1_sessions__session_id__events_tutorial_step_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['TutorialStepBody'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_file_api_v1_sessions__session_id__file_get: {
    parameters: {
      query: {
        /** @description Workspace-relative path to the file */
        path: string;
      };
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FileContent'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_file_api_v1_sessions__session_id__files_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FileWriteBody'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_revert_api_v1_sessions__session_id__files_revert_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['FileRevertBody'];
      };
    };
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_give_up_api_v1_sessions__session_id__give_up_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SubmissionRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_apply_patch_api_v1_sessions__session_id__patches__turn_id__apply_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
        turn_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['PatchResult'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_prompt_api_v1_sessions__session_id__prompts_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['PromptBody'];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['AgentTurnResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_reset_api_v1_sessions__session_id__reset_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SessionResetResponse'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_submission_api_v1_sessions__session_id__submission_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SubmissionRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  post_submit_api_v1_sessions__session_id__submit_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SubmissionRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_timeline_api_v1_sessions__session_id__timeline_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['SupervisionEventRead'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_tree_api_v1_sessions__session_id__tree_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FileTreeNodeSchema'][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  get_ws_token_api_v1_sessions__session_id__ws_token_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        session_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['WsTokenRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  status_v1_api_v1_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  get_verify_api_v1_verify__submission_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        submission_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['VerifyEnvelopeRead'];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['HTTPValidationError'];
        };
      };
    };
  };
  healthz_healthz_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
  healthz_ready_healthz_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': unknown;
        };
      };
    };
  };
  status_status_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': {
            [key: string]: unknown;
          };
        };
      };
    };
  };
}
