"""LLM-generated prose cache (P1 §0.4).

One canonical output per ``(domain, content_hash, prompt_version)`` tuple.
Bytes here are what downstream signatures (verify envelope, replay
artefact) hash against — never a live regeneration. To force a rescore
campaign across a domain, bump ``app.llm.domains.PROMPT_VERSION``: that
shifts every cache key under it, so old rows no longer match and the
next call re-generates using the live LLM. Old rows remain for audit.

The table is keyed by a composite unique constraint rather than relying
on natural-key uniqueness because cache_hash collisions are forbidden by
the SHA-256 input invariant but a single content_hash legitimately maps
to one row per ``(domain, prompt_version)`` slice.

SQLite divergence
-----------------
SQLite is reached via ``Base.metadata.create_all`` in
``tests/conftest.py`` (not Alembic). The ORM column types here
(``PG_UUID``, ``Text``) survive the ``_patch_models_for_sqlite`` shim;
the ``gen_random_uuid()`` server default is stripped to a Python-side
``uuid.uuid4`` factory by the same shim.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Integer, Text, UniqueConstraint, func
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class LLMCache(Base):
    """One LLM generation, keyed by canonicalised inputs + prompt version."""

    __tablename__ = "llm_cache"
    __table_args__ = (
        UniqueConstraint(
            "domain",
            "content_hash",
            "prompt_version",
            name="uq_llm_cache_lookup",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        server_default=func.gen_random_uuid(),
    )
    # Closed vocabulary; see ``app.llm.domains.LLMDomain``.
    domain: Mapped[str] = mapped_column(Text, nullable=False)
    # SHA-256 hex of the canonicalised inputs (see ``app.llm.hashing``).
    content_hash: Mapped[str] = mapped_column(Text, nullable=False)
    # Bumps invalidate every row under this domain; mirrors RUBRIC_VERSION.
    prompt_version: Mapped[int] = mapped_column(Integer, nullable=False)
    # Logical model id at write time (e.g. 'claude-haiku-4-5'); recorded so
    # re-judgement campaigns know what was used.
    model_id: Mapped[str] = mapped_column(Text, nullable=False)
    # Generated bytes, verbatim. Treated as opaque content.
    output: Mapped[str] = mapped_column(Text, nullable=False)
    input_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    output_tokens: Mapped[int | None] = mapped_column(Integer, nullable=True)
    generated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
    )

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<LLMCache domain={self.domain!r} "
            f"content_hash={self.content_hash[:8]}… "
            f"prompt_version={self.prompt_version}>"
        )
