"""Pydantic surfaces for ``GET /api/v1/me/recommendations`` (P1-2).

The wire format is intentionally compact: three items in steady state, one
diagnosis string, and a ``cache_hit`` flag the FE can use to instrument
warm-vs-cold UX. ``status`` is the discriminator between the shipped
recommendation cards and the ``coming_soon`` roadmap placeholders the FE
surfaces in the "every mission graded" edge case.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

RecommendationStatus = Literal["shipped", "coming_soon"]
RecommendationLanguage = Literal["typescript", "python", "go"]
RecommendationDifficulty = Literal["beginner", "intermediate", "advanced"]

# P1-2 — closed vocabulary that mirrors the grader's seven rubric
# dimensions (see :data:`app.grading.dimensions.RUBRIC_DIMENSIONS`). Pinned
# as a ``Literal`` so the FE gets a compile-time exhaustiveness check on
# the diagnosis copy switch — adding a new dimension forces both surfaces
# to update in lockstep.
WeakestDim = Literal[
    "final_correctness",
    "verification",
    "agent_review",
    "prompt_quality",
    "context_selection",
    "safety",
    "diff_minimality",
]


class RecommendationItem(BaseModel):
    """One ranked recommendation surfaced on the profile / catalog / report.

    ``why`` is the deterministic per-mission micro-prose generated by
    :mod:`app.recommendations.copy`. ``your_best_score`` is ``None`` when
    the user has never attempted the mission (the FE renders "Not yet
    attempted" in that case); ``your_attempts`` is the count of graded
    submissions against this mission for this user.
    """

    model_config = ConfigDict(extra="forbid")

    mission_id: str
    title: str
    language: RecommendationLanguage
    difficulty: RecommendationDifficulty
    why: str = Field(min_length=1)
    your_best_score: int | None = None
    your_attempts: int = 0
    status: RecommendationStatus = "shipped"
    target_release_date: str | None = None


class RecommendationSet(BaseModel):
    """Top-level response body — three items + the diagnosis + metadata.

    ``recommendations`` is constrained to at most 3 entries in steady
    state. The lower bound is 0 to cover the degenerate empty-catalogue
    case (the all-graded branch returns an empty list when the catalog
    has no missions at all) — the FE renders the diagnosis copy + a
    "nothing recommended right now" line on that path.
    """

    model_config = ConfigDict(extra="forbid")

    weakest_dim: WeakestDim | None = None
    diagnosis: str
    # Required (no default): the response ALWAYS carries this key — the
    # engine/cache builders pass it on every branch, and the all-graded
    # path passes an explicit ``[]``. ``min_length=0`` keeps the empty list
    # legal while ``required`` (no default_factory) makes the OpenAPI — and
    # therefore the generated FE type — treat it as always-present, matching
    # how RecommendationStrip / ReportView actually consume it.
    recommendations: list[RecommendationItem] = Field(min_length=0, max_length=3)
    computed_at: datetime
    cache_hit: bool


__all__ = [
    "RecommendationDifficulty",
    "RecommendationItem",
    "RecommendationLanguage",
    "RecommendationSet",
    "RecommendationStatus",
    "WeakestDim",
]
