"use client";

import * as React from "react";
import { Sparkles } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import {
  ApiError,
  getCoachingReflection,
  type CoachingReflection as CoachingReflectionPayload,
} from "@/lib/api";
import { Skeleton } from "@/components/ui/Skeleton";
import { track } from "@/lib/telemetry";
import { cn } from "@/lib/utils";

interface CoachingReflectionProps {
  submissionId: string;
  onScrollToEvent: (eventId: number) => void;
  onScrollToScratchpad: () => void;
}

/**
 * P1-4 — "// what you wrote vs. what you did" post-mortem section.
 *
 * Renders the per-submission coaching reflection that contrasts the
 * developer's scratchpad notes with the session's actual events. The
 * component is owner-only — the parent (PostMortemWalkthrough) only
 * mounts it for the owner, and the BE endpoint itself 403s a share
 * token even if one is somehow passed.
 *
 * Two pieces of behaviour live here:
 *
 *   * **Lazy fetch via IntersectionObserver.** We deliberately do NOT
 *     fire the network request on mount — coaching is generated by an
 *     LLM call (a cache miss is a real Bedrock invocation) so we only
 *     pay that cost when the user actually scrolls the section into
 *     view. ``coaching_reflection_shown`` telemetry fires once on
 *     first successful render so a funnel can split first-viewers
 *     from cache hits.
 *
 *   * **Inline-anchor parsing.** The BE prompt asks the model to embed
 *     ``[event:N]`` and ``[note:"<quote>"]`` markers. We split the
 *     reflection text on those markers and render each marker as a
 *     clickable anchor that hops the viewer to the timeline event /
 *     scratchpad section. ``coaching_reflection_anchor_clicked`` fires
 *     on click.
 *
 * When the BE returns ``reflection=null`` (the user opted out, has no
 * notes, OR the LLM was down), the component renders nothing — the
 * section is silently hidden, never an error toast.
 */
export function CoachingReflection({
  submissionId,
  onScrollToEvent,
  onScrollToScratchpad,
}: CoachingReflectionProps) {
  const sentinelRef = React.useRef<HTMLDivElement | null>(null);
  const [visible, setVisible] = React.useState(false);

  // Lazy-fetch trigger: flip ``visible`` to true on the first
  // intersection so the useQuery below is enabled exactly once.
  // SSR-safe: ``IntersectionObserver`` is gated behind ``window``.
  React.useEffect(() => {
    if (typeof window === "undefined") return;
    if (visible) return;
    const node = sentinelRef.current;
    if (!node) return;
    if (typeof window.IntersectionObserver === "undefined") {
      // Older / non-DOM test environments — eagerly enable so the
      // component still works rather than going dark.
      setVisible(true);
      return;
    }
    const obs = new window.IntersectionObserver(
      (entries) => {
        for (const entry of entries) {
          if (entry.isIntersecting) {
            setVisible(true);
            obs.disconnect();
            break;
          }
        }
      },
      { threshold: 0.5 },
    );
    obs.observe(node);
    return () => obs.disconnect();
  }, [visible]);

  const query = useQuery<CoachingReflectionPayload>({
    queryKey: ["coaching-reflection", submissionId],
    queryFn: ({ signal }) => getCoachingReflection(submissionId, signal),
    enabled: visible,
    // Coaching reflections are cached server-side — a refetch on
    // remount would be wasted work. Stale-time = Infinity keeps the
    // single fetch authoritative for the report page lifetime.
    staleTime: Number.POSITIVE_INFINITY,
    // 403 / 404 means the section will never load for this viewer —
    // no point in retrying. 0 (network) gets one retry by the default
    // React Query policy.
    retry: (failureCount, error) => {
      if (error instanceof ApiError) {
        if (error.status === 403 || error.status === 404) return false;
      }
      return failureCount < 1;
    },
  });

  // Telemetry: fire ``coaching_reflection_shown`` exactly once when
  // the section first renders with a non-null reflection. The dedupe
  // key is keyed on submission so a remount under React StrictMode
  // doesn't double-fire.
  const trackedRef = React.useRef<string | null>(null);
  React.useEffect(() => {
    const reflection = query.data?.reflection;
    if (!reflection) return;
    if (trackedRef.current === submissionId) return;
    trackedRef.current = submissionId;
    track("coaching_reflection_shown", {
      submission_id: submissionId,
      cached: Boolean(query.data?.cached),
    });
  }, [query.data, submissionId]);

  // Item 19 — observability. The user-facing behaviour is unchanged
  // (the section is silently hidden below), but we want oncall to be
  // able to spot a stale BE deploy or a degraded LLM path from the
  // analytics funnel without a log dive. Dedupe by submission so a
  // re-render under StrictMode doesn't double-fire the event.
  const errorTrackedRef = React.useRef<string | null>(null);
  React.useEffect(() => {
    if (!query.isError) return;
    if (errorTrackedRef.current === submissionId) return;
    errorTrackedRef.current = submissionId;
    const err = query.error;
    const status =
      err instanceof ApiError ? err.status : 0;
    if (process.env.NODE_ENV !== "production") {
      console.warn("CoachingReflection: fetch failed", err);
    }
    track("coaching_reflection_failed", { status });
  }, [query.isError, query.error, submissionId]);

  // The sentinel is a tiny invisible div that always renders so the
  // IntersectionObserver has a node to watch even before the section
  // body decides what to show.
  const sentinel = (
    <div
      ref={sentinelRef}
      aria-hidden
      style={{ height: 1, width: 1 }}
      data-testid="coaching-reflection-sentinel"
    />
  );

  if (!visible || query.isLoading) {
    return (
      <section
        aria-label="Coaching reflection"
        data-testid="coaching-reflection"
        className="rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] p-4"
      >
        {sentinel}
        <Skeleton className="h-3 w-32 rounded-sm" />
        <Skeleton className="mt-3 h-16 w-full rounded-sm" />
      </section>
    );
  }

  // Errors that we don't translate to a "hide me" (network, 5xx
  // other than llm_unavailable) — still render nothing so the
  // post-mortem stays calm. The error is reported via the React
  // Query devtools / a console warning, not toasted.
  if (query.isError || !query.data || !query.data.reflection) {
    return sentinel;
  }

  const payload = query.data;
  const segments = parseAnchorSegments(payload.reflection ?? "");

  const handleAnchorClick = (
    kind: "timeline" | "note_quote",
    value: string,
  ) => {
    if (kind === "timeline") {
      const eventId = Number.parseInt(value, 10);
      if (Number.isFinite(eventId)) {
        track("coaching_reflection_anchor_clicked", {
          submission_id: submissionId,
          anchor_kind: "timeline",
          event_id: eventId,
        });
        onScrollToEvent(eventId);
      }
      return;
    }
    track("coaching_reflection_anchor_clicked", {
      submission_id: submissionId,
      anchor_kind: "note_quote",
    });
    onScrollToScratchpad();
  };

  return (
    <section
      aria-label="Coaching reflection"
      data-testid="coaching-reflection"
      className="rounded-lg border border-[var(--color-border-strong)] bg-[var(--color-surface)] p-4 shadow-sm"
    >
      {sentinel}
      <header className="mb-3 inline-flex items-center gap-2 font-mono text-[10px] uppercase tracking-[0.18em] text-[var(--color-muted-foreground)]">
        <Sparkles className="size-3.5" aria-hidden />
        <span>{"// what you wrote vs. what you did"}</span>
      </header>
      <p
        className="text-sm leading-relaxed text-[var(--color-foreground)]"
        data-testid="coaching-reflection-body"
      >
        {segments.map((seg, i) => {
          if (seg.kind === "text") {
            return (
              <React.Fragment key={i}>{seg.value}</React.Fragment>
            );
          }
          if (seg.kind === "event") {
            return (
              <button
                key={i}
                type="button"
                data-testid="coaching-anchor-event"
                data-event-id={seg.value}
                onClick={() => handleAnchorClick("timeline", seg.value)}
                className={cn(
                  "mx-0.5 inline-flex items-center gap-0.5 rounded border",
                  "border-[var(--color-border-strong)] bg-[var(--color-surface)]",
                  "px-1 py-0 font-mono text-[11px] text-[var(--color-primary)]",
                  "transition-colors duration-150 ease-macos motion-reduce:transition-none",
                  "hover:border-[var(--color-primary)]",
                  "focus-visible:outline-none focus-visible:ring-2",
                  "focus-visible:ring-[var(--color-ring)] focus-visible:ring-offset-1 focus-visible:ring-offset-[var(--color-surface)]",
                )}
              >
                ↳ event #{seg.value}
              </button>
            );
          }
          // note_quote
          return (
            <button
              key={i}
              type="button"
              data-testid="coaching-anchor-note"
              data-note-quote={seg.value}
              onClick={() => handleAnchorClick("note_quote", seg.value)}
              className={cn(
                "mx-0.5 inline italic text-[var(--color-primary)] underline",
                "decoration-dotted underline-offset-4",
                "transition-colors duration-150 ease-macos motion-reduce:transition-none",
                "hover:text-[var(--color-foreground)]",
                "focus-visible:outline-none focus-visible:ring-2",
                "focus-visible:ring-[var(--color-ring)] focus-visible:ring-offset-1 focus-visible:ring-offset-[var(--color-surface)]",
              )}
            >
              &ldquo;{seg.value}&rdquo;
            </button>
          );
        })}
      </p>
    </section>
  );
}

// ---------------------------------------------------------------------------
// Anchor parsing
// ---------------------------------------------------------------------------

type Segment =
  | { kind: "text"; value: string }
  | { kind: "event"; value: string }
  | { kind: "note_quote"; value: string };

// Combined regex matches either ``[event:N]`` or ``[note:"..."]``. We
// capture each as a single alternation group so a single ``exec`` walk
// produces the same shape regardless of which marker fired.
const ANCHOR_RE = /\[event:(\d+)\]|\[note:"([^"\]]{1,160})"\]/g;

/**
 * Split a reflection string into a list of text / event / note
 * segments. The regex matches ``[event:N]`` or ``[note:"..."]``;
 * anything else (including markdown punctuation) stays in a ``text``
 * segment. Exported for unit-testing in isolation.
 */
export function parseAnchorSegments(text: string): Segment[] {
  if (!text) return [];
  const out: Segment[] = [];
  let cursor = 0;
  ANCHOR_RE.lastIndex = 0;
  let match: RegExpExecArray | null;
  while ((match = ANCHOR_RE.exec(text)) !== null) {
    if (match.index > cursor) {
      out.push({ kind: "text", value: text.slice(cursor, match.index) });
    }
    if (match[1] !== undefined) {
      out.push({ kind: "event", value: match[1] });
    } else if (match[2] !== undefined) {
      out.push({ kind: "note_quote", value: match[2] });
    }
    cursor = match.index + match[0].length;
  }
  if (cursor < text.length) {
    out.push({ kind: "text", value: text.slice(cursor) });
  }
  return out;
}
